### ISSUE TITLE
[spike] Decide on how to package and deploy the pipeline manifests

### ISSUE THREAD

**Issue by codificat** [thoth-station/opendatahub-cnbi#10]
At the time of this writing, the pipeline manifests for the CNBi feature implemented via the Meteor operator are added in the operator's repo under the `hack/` directory and deployed via the `Makefile`.

The pipelines should eventually be properly packaged and deployed.

Options:

- Use the [helm-charts repository](https://github.com/thoth-station/helm-charts/) as the source for all pipeline manifests, and deploy them via:
  - helm
  - KfDef
  - ArgoCD
- Have the operator deploy the manifests itself
- Keep the manifests in the [operator repo](https://github.com/AICoE/meteor-operator), deploy them via:
  - KfDef
  - ArgoCD

**Comment by codificat** [comment]
Trying again:
/sig devsecops
/kind feature
/priority important-longterm

**Comment by VannTen** [comment]
>     * Have the operator deploy the manifests itself

Many k8s operators appears to do that, but in my opinion they should not. The Roles needed for installing and running are not the same.


>     * Use the [helm-charts repository](https://github.com/thoth-station/helm-charts/) as the source for all pipeline manifests, and deploy them via:
>     * Keep the manifests in the [operator repo](https://github.com/AICoE/meteor-operator), deploy them via:

Is is a good resume to say that those two options bog down to bundle the pipelines with the operator, or separately ?
If that's the case, I think the decision depends on whether we see the operator as extendable or not. 
=> Does each Pipeline constitutes a plugin to make the operator able to handle a particular CR type (PackageList/GitRepo/whatever) ? Or do we have a bounded set of types (and hence of handlers).

Note that we could combine the two.

**Comment by VannTen** [comment]
Note from the meeting yesterday: might have some troubles using KfDef since it's using kustomize which is less powerful (if simpler) than something like helm (=> array merging in yaml)

**Comment by harshad16** [comment]
Based on the previous discussions in CNBI meetings.
The consensus of having the pipelines with cnbi operator was picked up.
with [#29](https://github.com/thoth-station/opendatahub-cnbi/pull/29) and [#108](https://github.com/thoth-station/meteor-operator/pull/108) this would be implemented.

**Comment by codificat** [comment]
/reopen
pending the merge of https://github.com/thoth-station/meteor-operator/pull/108

**Comment by harshad16** [comment]
Removed the revised-size as the issue is yet to be marked done.
