### ISSUE TITLE
UX/UI: make the mockups work with the CNBi operator

### ISSUE THREAD

**Issue by codificat** [thoth-station/opendatahub-cnbi#17]
## Goal

Following from #18, expand the ODH dashboard to include the [Custom Notebook Image (CNBi) use cases](https://issues.redhat.com/browse/RHODS-3203).

This includes:
- implementing the [UI mock-ups](https://marvelapp.com/prototype/181i9844/screen/88394979) for the Package List and extend image use cases
- integrate the BYON import functionality (#18) with this new/expanded UI
- have the dashboard interact with the meteor-operator to manage Custom Notebook resources
- add any appropriate integrations with the Thoth API, e.g. to help determine valid/known package versions

## Acceptance criteria

- [x] the odh-dashboard UI frontend implements the design mockups for CNBi (https://github.com/thoth-station/opendatahub-cnbi/issues/18)
  - This includes the integration of the BYON import functionality  with this new/expanded UI
- [x] https://github.com/thoth-station/odh-dashboard/issues/7
  - **NOTE**: this depends on the operator handling all the CNBi use cases:
    - https://github.com/thoth-station/helm-charts/issues/48
- [ ] Thoth is used to help refine the specific package versions
- [ ] Thoth is used to provide enviroment options for build form

**Comment by Gkrumbach07** [comment]
This issue will most likely be an EPIC as it involves implementing the mockup UI and connecting that to the CNBi operator.
- [ ] https://github.com/thoth-station/opendatahub-cnbi/issues/18
- [ ] connect the CNBI operator to the UI and depreciate the old BYON functionality

**Comment by Gkrumbach07** [comment]
WIP

depends on https://github.com/thoth-station/opendatahub-cnbi/issues/18

**Acceptance Criteria**
- implement the mockup for CNBi UI

**Comment by codificat** [comment]
The various odh-dashboard tasks are now complete (see linked issues).

The items that involve Thoth mentioned in the issue description should be handled moving forward in #27

/close
