### ISSUE TITLE
UX/UI: change the BYON UI to work with CNBi (odh)

### ISSUE THREAD

**Issue by codificat** [thoth-station/opendatahub-cnbi#18]
## Goal

To update the ODH dashboard code that implements the BYON functionality to incorporate the [UI mockups](https://marvelapp.com/prototype/181i9844/screen/88394979).

This includes:
- adding the frontend designs for Custom Notebook images (CNBi) from the mockups
- changing the existing BYON UI design in ODH 1.3/1.4 to be integrated with all the CNBi use cases

## Acceptance Criteria

   * [x] CNBi use cases have a (frontend) UI in the ODH dashboard
   * [x] BYON functionality is integrated within the new CNBi UI

<img alt="image" width="1038" src="https://user-images.githubusercontent.com/12587674/193831510-869b3d9e-c378-4037-a425-6f75921b2511.png">

## Additional info

The backend modifications so that the dashboard interacts with the CNBi operator instead of Tekton PipelineRuns are covered by https://github.com/thoth-station/odh-dashboard/issues/7

**Comment by Gkrumbach07** [comment]
Implement a non functioning alpha version of the CNBi mockup [here](https://github.com/opendatahub-io/odh-dashboard/tree/BYON), while keeping the original functionality of BYON until it is connected to CNBi operator.

Story Points Estimate [5-8pt]

**Comment by Gkrumbach07** [comment]
is this issue solved by https://github.com/thoth-station/odh-dashboard/pull/4

**Comment by codificat** [comment]
thanks!

I updated the issue description to better match the work here. The description is a summary - see https://github.com/thoth-station/odh-dashboard/pull/4 for the details of what was implemented.

/close
