### ISSUE TITLE
Make the deployment compatible with ODH and ArgoCD for op1st / OSC cluster

### ISSUE THREAD

**Issue by codificat** [thoth-station/opendatahub-cnbi#20]
## Problem statement

Continuation of https://github.com/open-services-group/scrum/issues/37

As a BYON/CNBi developer,
I want ArgoCD to manage all the required components in the dev environment
so that when I contribute changes they are automatically applied to the environment and become available for testing, demos, etc

## Acceptance criteria

The following components should be deployed by ArgoCD to the `odh-cl1` cluster, in the `opf-jupyterhub-stage namespace`:

- [x] the BYON development version of the ODH dashboard
- [x] all the tekton pipelines and tasks required: https://github.com/thoth-station/opendatahub-cnbi/issues/10
- [x] the CNBi controller: https://github.com/thoth-station/meteor-operator/issues/88

Also:
- [x] a process is in place to make sure the components are updated when devs implement changes to them
- [x] documentation for the CD environment is available and reflects the process and components mentioned above

**Comment by harshad16** [comment]
Based on the previous discussion, we wanted the odh-dashboard with the latest tag to be deployed on the demo cluster.
we have observed the error list:
```
{"level":50,"time":1667240031375,"pid":80,"hostname":"odh-dashboard-b45c86b6-7p264","msg":"Error fetching applications: odhapplications.dashboard.opendatahub.io is forbidden: User \"system:serviceaccount:opf-jupyterhub-stage:odh-dashboard\" cannot list resource \"odhapplications\" in API group \"dashboard.opendatahub.io\" in the namespace \"opf-jupyterhub-stage\""}
{"level":50,"time":1667240031378,"pid":80,"hostname":"odh-dashboard-b45c86b6-7p264","msg":"Error fetching applications: odhapplications.dashboard.opendatahub.io is forbidden: User \"system:serviceaccount:opf-jupyterhub-stage:odh-dashboard\" cannot list resource \"odhapplications\" in API group \"dashboard.opendatahub.io\" in the namespace \"opf-jupyterhub-stage\""}
{"level":50,"time":1667240031381,"pid":80,"hostname":"odh-dashboard-b45c86b6-7p264","msg":"Error fetching applications: odhapplications.dashboard.opendatahub.io is forbidden: User \"system:serviceaccount:opf-jupyterhub-stage:odh-dashboard\" cannot list resource \"odhapplications\" in API group \"dashboard.opendatahub.io\" in the namespace \"opf-jupyterhub-stage\""}
{"level":50,"time":1667240031390,"pid":80,"hostname":"odh-dashboard-b45c86b6-7p264","msg":"Error fetching quick starts: odhquickstarts.console.openshift.io is forbidden: User \"system:serviceaccount:opf-jupyterhub-stage:odh-dashboard\" cannot list resource \"odhquickstarts\" in API group \"console.openshift.io\" in the namespace \"opf-jupyterhub-stage\""}
{"level":50,"time":1667240031402,"pid":80,"hostname":"odh-dashboard-b45c86b6-7p264","msg":"Error fetching documentation resources: odhdocuments.dashboard.opendatahub.io is forbidden: User \"system:serviceaccount:opf-jupyterhub-stage:odh-dashboard\" cannot list resource \"odhdocuments\" in API group \"dashboard.opendatahub.io\" in the namespace \"opf-jupyterhub-stage\""}
...
```

The reason for this error in odh-dashboard is due to the new crds, which are not yet available
https://github.com/opendatahub-io/opendatahub-operator/issues/185

**Comment by codificat** [comment]
This is complete now: controller, pipelines and dashboard are deployed in the op1st/OSC cluster. The set up and places to update are documented [in this repo](https://github.com/thoth-station/opendatahub-cnbi/blob/2a73095feccf606375ee03c794aca2c6d4e76bda/docs/dev-test-env.md)

/close
